---



BASE_OUTPUT_DIR: /scratch/timshel/BMIcelltypes/190306_mb_replication_tmp


SPECIFICITY_INPUT:
  - id: mousebrain190306
    path: /nfsdata/projects/timshel/sc-genetics/timshel-bmicelltypes2019/src/validate-cellect/data-190306/specificity_matrix.mousebrain_all_190306_es_fix.csv.gz


GWAS_SUMSTATS:
  - id: BMI_UKBB_Loh2018
    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/BMI_UKBB_Loh2018.sumstats.gz
  



ANALYSIS_TYPE: 
  prioritization: True
  conditional: False
  heritability: False
  heritability_intervals: False


WINDOW_DEFINITION: 
  WINDOW_SIZE_KB:
    100
  WINDOW_LD_BASED: 
    False



LDSC_CONST:
  DATA_DIR: 
    data/ldsc
  LDSC_DIR: 
    ldsc
  NUMPY_CORES: 
    1
